#!/bin/sh


#sh ./unzipper.sh #executes the unzipper script


cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication surfaceFeatureExtract

runApplication blockMesh 

runApplication snappyHexMesh -overwrite

#Checkmesh
runApplication checkMesh

# Decompose
# runApplication decomposePar

# Run
#runApplication mpirun -np 24 pisoFoam -parallel

# Reconstruct
#runApplication reconstructPar

# paraFoam

#------------------------------------------------------------------------------
